In [39]:
import tensorflow as tf
import numpy as np
tf.keras.backend.set_floatx('float64')

In [23]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [24]:
print(type(x_test), x_test.shape)

# convert to floating-point numbers
x_train, x_test = x_train / 255.0, x_test / 255.0

<class 'numpy.ndarray'> (10000, 28, 28)


In [25]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [28]:
print(x_train[:1].shape)
predictions = model(x_train[:1]).numpy()
print(predictions.shape)
predictions

(1, 28, 28)
(1, 10)


array([[ 0.12791818, -0.04258245,  0.52494185,  0.11280438,  0.0072788 ,
         0.49925071,  0.02496045,  0.04695788,  0.87702024, -0.20152661]])

In [31]:
tf.nn.softmax(predictions).numpy()

array([[0.08841365, 0.07455415, 0.13150568, 0.08708743, 0.07836575,
        0.12817018, 0.07976371, 0.08153775, 0.18700371, 0.06359797]])

In [41]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss1 = loss_fn(y_train[:1], predictions).numpy()
loss2 = -np.log(1/10)
print(loss1, loss2)

2.054396390914917 2.3025850929940455


In [53]:
# Training
model.compile(optimizer='adam', 
              loss=loss_fn, 
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 21s 345us/sample - loss: 0.0673 - accuracy: 0.9782
Epoch 2/5
60000/60000 [==============================] - 20s 338us/sample - loss: 0.0603 - accuracy: 0.9807
Epoch 3/5
60000/60000 [==============================] - 19s 313us/sample - loss: 0.0525 - accuracy: 0.9829
Epoch 4/5
60000/60000 [==============================] - 25s 409us/sample - loss: 0.0482 - accuracy: 0.9838
Epoch 5/5
60000/60000 [==============================] - 18s 306us/sample - loss: 0.0426 - accuracy: 0.9856


In [47]:
# Evaluating
model.evaluate(x_test, y_test, verbose=2)

10000/10000 - 1s - loss: 0.0793 - accuracy: 0.9742


[0.07931530644902399, 0.9742]

In [48]:
prob_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [52]:
prob_model(x_test[:5]).numpy()

array([[5.26429055e-07, 1.35682188e-08, 4.11555548e-06, 1.12572166e-04,
        3.97678350e-11, 2.55978059e-07, 4.91322300e-11, 9.99879726e-01,
        2.10434816e-07, 2.58018154e-06],
       [6.92606592e-11, 2.61352715e-04, 9.99700953e-01, 3.01709345e-06,
        2.51317876e-14, 2.72054535e-05, 1.16965836e-07, 1.11194925e-11,
        7.35465546e-06, 1.25681953e-12],
       [7.84550534e-09, 9.98771628e-01, 2.52238802e-04, 5.45237382e-06,
        1.32242296e-05, 1.71591532e-06, 3.80728172e-06, 7.77487054e-04,
        1.74207327e-04, 2.30894589e-07],
       [9.99914902e-01, 4.74302525e-09, 5.72856833e-06, 1.71181292e-07,
        1.19839204e-07, 5.26198687e-06, 5.38582249e-05, 5.12283787e-06,
        6.43206831e-07, 1.41876313e-05],
       [7.56453371e-06, 2.67344286e-09, 3.03998166e-05, 4.52480295e-08,
        9.75439383e-01, 3.82708544e-07, 5.35563710e-05, 2.61868130e-05,
        6.12503027e-07, 2.44418665e-02]])